---
- hosts: all
  gather_facts: no
  vars:
    media_root: /var/main

  vars_files:
    - vars/users.yml
    - vars/shares.yml

  tasks:
    - import_tasks: tasks/update-system.yml
    - import_tasks: tasks/ufw.yml
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/samba.yml
    - import_tasks: tasks/qbittorrent.yml
    - import_tasks: tasks/plex.yml
    - import_tasks: tasks/nginx.yml
    - import_tasks: tasks/certbot.yml

  handlers:
    - import_tasks: handlers/services.yml
