---
- name: install prerequisites
  apt:
    name: software-properties-common
    state: latest
- name: enable universe repository
  shell: "add-apt-repository universe"
- name: ensure certbot is installed
  apt:
    name: certbot
    update_cache: yes
    state: latest
- name: ensure certbox nginx plugin is installed
  apt:
    name: python3-certbot-nginx
    state: latest
- name: configure SSL certificate for nginx
  shell: "certbot --nginx -m vaicys@gmail.com --agree-tos -d {{ inventory_hostname }} -n"
- name: schedule certbot renewal
  cron:
    name: Certbot certificate renewal
    job: certbot renew --post-hook "systemctl reload nginx.service"
    special_time: weekly
