---
- name: ensure nginx is installed
  apt:
    name: nginx
    state: latest
- name: configure nginx
  template:
    src: templates/nginx-default-site.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: ensure nginx is running
  service:
    name: nginx
    state: started
