---
- name: add plex repository key
  shell: "curl https://downloads.plex.tv/plex-keys/PlexSign.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/plex.gpg"
  args:
    warn: no

- name: add plex repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: ensure plex media server is installed
  apt:
    name: plexmediaserver
    state: latest

- name: reconfigure storage location
  service:
    name: plexmediaserver
    state: stopped

- name: set correct owner and group
  file:
    path: "{{ media_root }}/plexmediaserver"
    recurse: yes
    owner: plex
    group: plex
    mode: 02775
    state: directory

- file:
    path: /var/lib/plexmediaserver
    state: absent

- file:
    src: "{{ media_root }}/plexmediaserver"
    dest: /var/lib/plexmediaserver
    group: plex
    state: link

- name: ensure plex media server is started
  service:
    name: plexmediaserver
    state: started

- name: add plex user to torrent-users
  user:
    name: plex
    groups: torrent-users
    append: yes
