---
- name: enable universe repository
  shell: "apt-add-repository ppa:qbittorrent-team/qbittorrent-stable -y"

- name: ensure qbittorrent is installed
  apt:
    name: qbittorrent-nox
    state: latest

- name: write qbittorrent service file
  template:
    src: templates/qbittorrent.service
    dest: /etc/systemd/system/qbittorrent.service

- name: create temp path
  file:
    path: "{{ media_root }}/Incoming/temp"
    group: torrent-users
    state: directory
    mode: 02775

- name: reload systemctl daemon
  shell: systemctl daemon-reload

- name: create configuration path
  file:
    path: /home/qbittorrent/.config/qBittorrent
    state: directory
    owner: qbittorrent
    group: qbittorrent
    mode: 0755

- name: configure qbittorrent
  template:
    src: templates/qbittorrent.conf.j2
    dest: /home/qbittorrent/.config/qBittorrent/qBittorrent.conf
  notify:
    - restart qbittorrent

- name: ensure qbittorrent is running
  service:
    name: qbittorrent
    enabled: yes
    state: started
