---
- name: ensure uncomplicated firewall is installed
  apt:
    name: ufw
    state: latest

- ufw:
    state: reset

# OpenSSH
- ufw:
    rule: allow
    proto: tcp
    port: "22"
# NGINX
- ufw:
    rule: allow
    proto: tcp
    port: "80"
- ufw:
    rule: allow
    proto: tcp
    port: "443"
# Samba
- ufw:
    rule: allow
    proto: udp
    port: "137:138"
- ufw:
    rule: allow
    proto: tcp
    port: "139"
- ufw:
    rule: allow
    proto: tcp
    port: "445"
# qBittorrent
- ufw:
    rule: allow
    port: "8999"
# PLEX
- ufw:
    rule: allow
    proto: tcp
    port: "32400"

- ufw:
    policy: allow
    direction: outgoing
- ufw:
    policy: deny
    direction: incoming
- ufw:
    state: enabled
  notify:
    - restart ufw
