---
- name: ensure uncomplicated firewall is installed
  apt:
    name: ufw
    state: latest

- ufw: reset state
    state: reset

# OpenSSH
- ufw:
    rule: allow
    proto: tcp
    port: "22"
# NGINX
- ufw:
    rule: allow
    proto: tcp
    port: "80"
- ufw:
    rule: allow
    proto: tcp
    port: "443"
# Samba
- ufw:
    rule: allow
    proto: udp
    port: "137:138"
- ufw:
    rule: allow
    proto: tcp
    port: "139"
- ufw:
    rule: allow
    proto: tcp
    port: "445"
# qBittorrent
- ufw:
    rule: allow
    port: "8999"
# PLEX
- ufw:
    rule: allow
    proto: tcp
    port: "32400"

- ufw:
    policy: allow
    direction: outgoing
- ufw:
    policy: deny
    direction: incoming
- name: reconfigure kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
- name: enable firewall
  ufw:
    state: enabled
