---
- name: create groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"
  loop_control:
    label: group

- name: create user accounts
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users }}"
  loop_control:
    label: user
  when: item.groups is defined

- name: set user shell
  user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
  loop: "{{ users }}"
  loop_control:
    label: user
  when: item.shell is defined

- name: create groupless user accounts
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
  loop: "{{ users }}"
  loop_control:
    label: user
  when: item.groups is not defined
