---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart qbittorrent
  service:
    name: qbittorrent
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted
