---
- hosts: all
  tasks:
  - name: Add certbot stable upstream repository
    apt_repository:
      repo: 'ppa:certbot/certbot'
  - name: Ensure certbot is latest version
    apt:
      name: python-certbot-nginx
      state: latest
      update_cache: yes
  - name: Configure SSL certificate for nginx
    shell: certbot --nginx -m vaicys@gmail.com --agree-tos -d cronos.vaicys.com -n
  - name: Schedule certbot renewal
    cron:
      name: Certbot certificate renewal
      job: certbot renew --post-hook "systemctl reload nginx"
      special_time: weekly
