---
- hosts: all
  tasks:
  - name: Ensure uncomplicated firewall is at latest version
    apt:
      name: ufw
      state: latest
  - name: Configure firewall
    ufw:
      state: reset
  - ufw:
      state: enabled
  - ufw:
      logging: on
  # OpenSSH
  - ufw:
      rule: allow
      proto: tcp
      port: 22
  # NGINX
  - ufw:
      rule: allow
      proto: tcp
      port: 80
  - ufw:
      rule: allow
      proto: tcp
      port: 443
  # Samba
  - ufw:
      rule: allow
      proto: udp
      port: 137:138
  - ufw:
      rule: allow
      proto: tcp
      port: 139
  - ufw:
      rule: allow
      proto: tcp
      port: 445
  # qBittorrent
  - ufw:
      rule: allow
      port: 8999
  - ufw:
      policy: deny
      direction: incoming
  - ufw:
      policy: allow
      direction: outgoing
  - service:
      name: ufw
      state: restarted
