name: Deploy
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt secrets
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPTION_KEY }}"
          --output secrets.tar secrets.tar.gpg
      - name: Unpack secrets
        run: tar xvf secrets.tar
      - name: Add target to known hosts
        run: ssh-keyscan -H ${{ secrets.HOSTNAME }} > ~/.ssh/known_hosts
      - name: Ansible setup
        shell: bash
        run: echo "[defaults]" >> ansible.cfg;
          echo "deprecation_warnings=False" >> ansible.cfg
      - name: Install Ansible
        run: pip install ansible
      - name: Run Ansible playbook
        run: ansible-playbook -i "${{ secrets.HOSTNAME }}," --vault-password-file vault_key
          --private-key ansible-key.id_rsa -u root site.yml
